config/routes.rb
Spree::Core::Engine.routes.draw do
	post '/orders/:number/repeated_order' => 'repeated_orders#create', as: :repeat_order
	namespace :admin do
		resources :kitchens do
			member do
				post :inc_progress
			end
		end
	end
	

	namespace :home do
		post :checkPostcode
	end
end

app/views/spree/admin/shared/_configuration_menu.html.erb
<% content_for :sidebar_title do %>
  <%= Spree.t(:configurations) %>
<% end %>

<% content_for :sidebar do %>
  <nav class="menu">
    <ul class="sidebar" data-hook="admin_configurations_sidebar_menu">
      <%= configurations_sidebar_menu_item Spree.t(:general_settings), edit_admin_general_settings_path %>
      <% if Spree::Config[:override_actionmailer_config] %>
        <%= configurations_sidebar_menu_item Spree.t(:mail_method_settings), edit_admin_mail_method_path %>
      <% end %>
      <%= configurations_sidebar_menu_item Spree.t(:image_settings), edit_admin_image_settings_path %>
      <%= configurations_sidebar_menu_item Spree.t(:payment_methods), admin_payment_methods_path %>
      <%= configurations_sidebar_menu_item Spree.t(:taxonomies), admin_taxonomies_path %>
      <%= configurations_sidebar_menu_item Spree.t(:shipping_methods), admin_shipping_methods_path %>
      <%= configurations_sidebar_menu_item Spree.t(:shipping_categories), admin_shipping_categories_path %>
      <%= configurations_sidebar_menu_item Spree.t(:analytics_trackers), admin_trackers_path %>
    </ul>
  </nav>
<% end %>

app/views/spree/admin/shared/_configuration_menu_html.erb
<% content_for :sidebar_title do %>
  <%= Spree.t(:configurations) %>
<% end %>

<% content_for :sidebar do %>
  <nav class="menu">
    <ul class="sidebar" data-hook="admin_configurations_sidebar_menu">
      <%= configurations_sidebar_menu_item Spree.t(:general_settings), edit_admin_general_settings_path %>
      <% if Spree::Config[:override_actionmailer_config] %>
        <%= configurations_sidebar_menu_item Spree.t(:mail_method_settings), edit_admin_mail_method_path %>
      <% end %>
      <%= configurations_sidebar_menu_item Spree.t(:image_settings), edit_admin_image_settings_path %>
      <%= configurations_sidebar_menu_item Spree.t(:payment_methods), admin_payment_methods_path %>
      <%= configurations_sidebar_menu_item Spree.t(:taxonomies), admin_taxonomies_path %>
      <%= configurations_sidebar_menu_item Spree.t(:shipping_methods), admin_shipping_methods_path %>
      <%= configurations_sidebar_menu_item Spree.t(:shipping_categories), admin_shipping_categories_path %>
      <%= configurations_sidebar_menu_item Spree.t(:analytics_trackers), admin_trackers_path %>
    </ul>
  </nav>
<% end %>

app/views/spree/admin/shared/_content_header.html.erb
<% if content_for?(:page_title) || content_for?(:page_actions) %>
<% if content_for?(:page_title) %>
    <h1 class="page-title <%= yield :page_title_classes %>"><%= yield :page_title %></h1>
<% end %>

<% if content_for?(:page_actions) %>
<ul class="inline-menu pull-right">
    <%= yield :page_actions %>
</ul>

<% end %>
<% end %>

app/views/spree/admin/shared/_head.html.erb
<meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />

<%= csrf_meta_tags %>

<title>
    <%= "Yoyo Burger" %>
    <%= Spree.t(controller.controller_name, :default => controller.controller_name.titleize) %>
  
</title>

<!-- Get "Open Sans" font from Google -->
<link href='//fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600&subset=latin,cyrillic,greek,vietnamese' rel='stylesheet' type='text/css'>

<%= stylesheet_link_tag 'admin/all' %>

<%= javascript_include_tag 'admin/all' %>

<%= render "spree/admin/shared/translations" %>
<%= render "spree/admin/shared/routes" %>

<%= javascript_tag do -%>
  jQuery.alerts.dialogClass = 'spree';
  <%== "var AUTH_TOKEN = #{form_authenticity_token.inspect};" %>
<% end -%>

<%= yield :head %>

app/views/spree/admin/shared/_header.html.erb
<header data-hook>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <a href="<%= root_url%>/admin" class="brand">
              <small>
                <i class="icon-shopping-cart"></i>
                YoYo Admin
              </small>
            </a><!--/.brand-->
            <ul class="nav ace-nav pull-right">
            	<nav data-hook="admin_login_navigation_bar" class="columns eleven"></nav>
              </ul><!--/.ace-nav-->
          </div><!--/.container-fluid-->
        </div><!--/.navbar-inner-->
      </div>
    </header>

app/views/spree/admin/shared/_menu.html.erb
<div class="sidebar" id="sidebar">
	<div class="sidebar-shortcuts" id="sidebar-shortcuts">
		<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
			<button class="btn btn-small btn-success">
				<i class="icon-signal"></i>
			</button>

			<button class="btn btn-small btn-info">
				<i class="icon-pencil"></i>
			</button>

			<button class="btn btn-small btn-warning">
				<i class="icon-group"></i>
			</button>

			<button class="btn btn-small btn-danger">
				<i class="icon-cogs"></i>
			</button>
		</div>

		<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
			<span class="btn btn-success"></span>

			<span class="btn btn-info"></span>

			<span class="btn btn-warning"></span>

			<span class="btn btn-danger"></span>
		</div>
	</div><!--#sidebar-shortcuts-->

	<ul data-hook="admin_tabs" class="nav nav-list">
		<%= render :partial => 'spree/admin/shared/tabs' %>
	</ul>

</div>


<!-- <nav id="admin-menu" data-hook>
	<div class="container">
		<div class="sixteen columns main-menu-wrapper">
			
		</div>
	</div>
</nav> -->

app/views/spree/admin/shared/_order.html.erb
<tr data-time="<%=order.created_at.to_i %>" data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %> table-row">
	<td class="expand-details"><span class="plus-minus"> + </span></td>
	<td class="align-center expand-details"><%= link_to order.number, edit_admin_order_path(order) %></td>
	<td class="align-center expand-details"><%= order.created_at.strftime("%I:%M %P")  %></td>
	<td class="align-center"><span class="state <%= order.payment_state %>"><%= link_to Spree.t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></span></td>
	<% if Spree::Order.checkout_step_names.include?(:delivery) %>
	<td class="align-center"><%= order.order_progress %></td>
	<% end %>
	<td class="align-center"><%= mail_to order.email %></td>
	<td class="align-center"><%= order.display_total.to_html %></td>
	<td class='actions align-center' data-hook="admin_orders_index_row_actions">


		<%= link_to "Cooked", inc_progress_admin_kitchen_path(:id => order.id), method: :post, :remote => true %>


	</td>

</tr>

<div>
	<thread>
		<tr style="display:none">
			<th></th>
			<th>Name</th>
			<th>Size/Variants</th>
			<th>Quantity</th>
		</tr>
	</thread>

	<% order.line_items.each do |item| %>
	<tr class="line-item" id="line-item-<%= item.id %>" style="display:none">
		<td></td>
		<td class="line-item-name">
			<%= item.variant.product.name %>
		</td>

		<td class="line-item-variant">
			<% if item.variant.option_values.empty? %>
			Standard
			<% else %>
			<%= variant_options(item.variant) %>
			<% end %>
		</td>

		<td class="line-item-qty-show align-center">
			<%= item.quantity %>
		</td>
	</tr>
	<% end %>
</div>

app/views/spree/admin/shared/_sidebar.html.erb
<% if content_for?(:sidebar) %>
<div class="page-header position-relative">
	<aside id="page-sub-menu" data-hook class="inline-menu">
		<%= yield :sidebar %>
	</aside>
</div>
<% end %>

app/views/spree/admin/shared/_sub_menu.html.erb
<% if content_for?(:sub_menu) %>
  <nav id="sub-menu-my" data-hook>
    <div class="container">
        <%= yield :sub_menu %>
    </div>
  </nav>
<% end %>

app/views/spree/admin/shared/_tabs.html.erb
<% if can? :admin, Spree::Order %>
  <%= tab :orders, :payments, :creditcard_payments, :shipments, :credit_cards, :return_authorizations, :icon => 'icon-shopping-cart' %>
<% end %>
<% if can? :admin, Spree::Product %>
  <%= tab :products, :option_types, :properties, :prototypes, :variants, :product_properties, :taxonomies, :icon => 'icon-th-large' %>
<% end %>
<%= tab('Kitchen', :url => "/admin/kitchens", :icon => 'icon-food') %>
<%= tab('Reports',:target=>'_blank', :url =>"https://accounts.google.com/ServiceLogin?service=analytics&passive=true&nui=1&hl=en&continue=https%3A%2F%2Fwww.google.com%2Fanalytics%2Fweb%2F%3Fhl%3Den&followup=https%3A%2F%2Fwww.google.com%2Fanalytics%2Fweb%2F%3Fhl%3Den", :icon => 'icon-signal') %>
<%= tab :configurations, :general_settings, :mail_methods, :tax_categories, :tax_rates, :tax_settings, :zones, :countries, :states, :payment_methods, :shipping_methods, :shipping_categories, :stock_transfers, :stock_locations, :trackers, :label => 'configuration', :icon => 'icon-wrench', :url => spree.edit_admin_general_settings_path %>
<% if can? :admin, Spree::Promotion %>
  <%= tab(:promotions, :url => spree.admin_promotions_path, :icon => 'icon-bullhorn') %>
<% end %>